### ISSUE TITLE
How to enable darkMode?

### ISSUE THREAD

**Issue by kobzarchekg** [catppuccin/qutebrowser#1]
When i enable darkMode in Qutebrowser all pages look is terrible with black bg color.

**Comment by nekowinston** [comment]
Is this about `colors.webpage.darkmode.enabled`? I'm using it with a minimal config right now and can't find issues.

**Comment by nekowinston** [comment]
Ah, apologies, after a restart I can see the issue, but I doubt that it's specific to this theme; please have a look at https://github.com/qutebrowser/qutebrowser/discussions/5733 or similar.
